### ISSUE TITLE
Test cases are failing while downloading required artifacts from bintry

### ISSUE THREAD

**Issue by podile** [spring-cloud-stream-app-starters/tensorflow#42]
Some test cases are failing while downloading required artifacts from bintry. It seems to be permissions issue, can someone please help resolving the issues?

`Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/big-data/generic/imagenet_comp_graph_label_strings.txt
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:173)
	at org.springframework.cloud.stream.app.image.recognition.processor.ImageRecognitionTensorflowOutputConverter.<init>(ImageRecognitionTensorflowOutputConverter.java:51)
	... 68 more
`

**Comment by sabbyanandan** [comment]
Hi, @podile. Can you share more details as to how you're running the tests?

**Comment by tzolov** [comment]
This problem was caused by some Bintry throttling polices. It is resolved now.
